config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'

  get 'merchants/edibles' => 'merchants#edibles'
  get 'merchants/concentrates' => 'merchants#concentrates'
  get 'flowers/all' => 'flowers#all'
  get 'admin' => 'admin#panel'

  resources :merchants do
    get 'edibles/all' => 'edibles#all'
    get 'concentrates/all' => 'concentrates#all'
    resources :edibles
    resources :concentrates
    resources :flowers, only: [:show, :index]
  end

  resources :flowers
  get 'equipment/all' => 'equipment#all'
  resources :equipment

end

app/models/concentrate.rb
class Concentrate < ActiveRecord::Base
	belongs_to :merchant

	validates :strain, presence: true
	validates :kind, presence: true
	validates :quantity_price, presence: true
end

app/models/edible.rb
class Edible < ActiveRecord::Base
	belongs_to :merchant

	validates :name, presence: true
	validates :description, presence: true
	validates :price, presence: true

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  belongs_to :merchant

  validates :item, presence: true
  validates :price, presence: true
  validates :kind, presence: true
end

app/models/flower.rb
class Flower < ActiveRecord::Base
	belongs_to :merchant

	validates :strain, presence: true
	validates :kind, presence: true
	validates :quantity_price, presence: true
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
	has_many :flowers
	has_many :concentrates
	has_many :edibles
	has_many :equipments

	validates :name, presence: true
	validates :phone, presence: true
	validates :email, presence: true
	validates :email, format: { with: /.+@.+\..+/i, message: "improper format" }

	def self.edible_companies
		self.includes(:edibles).order('premium DESC').each_with_object([]) {|m, a| m.edibles.any? ? a << m : false }
	end

	def self.active_edible_companies
		self.includes(:edibles).order('premium DESC').where( edibles: {display: true} )
	end

	def self.concentrate_companies
		self.includes(:concentrates).order('premium DESC').each_with_object([]) {|m, a| m.concentrates.any? ? a << m : false }
	end

	def self.active_concentrate_companies
		self.includes(:concentrates).order('premium DESC').where( concentrates: {display: true} )
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :admin, :premium]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
  	self.role ||= :user
  end

  def set_premium_role!
  	self.role = :premium
  	self.save
  end

  def set_user_role!
  	self.role = :user
  	self.save
  end

  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!

	def panel
		authorize User
		@concentrates = Merchant.concentrate_companies
		@edibles = Merchant.edible_companies
	end

end

app/controllers/edibles_controller.rb
class EdiblesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :all]

	def index
		@merchant = Merchant.find(params[:merchant_id])
	end

	def all
		@merchant = Merchant.find(params[:merchant_id])
	end

	def show
		@edible = Edible.find(params[:id])
	end

	def new
		authorize User
		@merchant = Merchant.find(params[:merchant_id])
		@edible = Edible.new
	end

	def create
		authorize User
		@merchant = Merchant.find(params[:merchant_id])
		@edible = Edible.new(edible_params)
		if @edible.save
			@merchant.edibles << @edible
			redirect_to merchant_edible_path(@merchant, @edible)
		else
			render 'new'
		end
	end

	def edit
		authorize User
		@edible = Edible.find(params[:id])
		@merchant = Merchant.find(params[:merchant_id])
	end

	def update
		authorize User
		@edible = Edible.find(params[:id])
		@merchant = Merchant.find(params[:merchant_id])
		if @edible.update(edible_params)
			redirect_to merchant_edible_path(@merchant, @edible)
		else
			render 'edit'
		end
	end

	private

	def edible_params
		params.require(:edible).permit(:name, :description, :price, :display, :rec_med)
	end

end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :all]

	def index
		@equipments = Equipment.where(display: true)
	end

	def all
		@equipments = Equipment.all
		render :index
	end

	def show
		@equipment = Equipment.find(params[:id])
	end

	def new
		authorize User
		@equipment = Equipment.new
	end

	def edit
		authorize User
		@equipment = Equipment.find(params[:id])
	end

	def create
		authorize User
		@equipment = Equipment.new(equipment_params)
		if @equipment.save
			get_merchant(@equipment)
			redirect_to @equipment
		else
			render 'new'
		end
	end

	def update
		authorize User
		@equipment = Equipment.find(params[:id])
		if @equipment.update(equipment_params)
			get_merchant(@equipment)
			redirect_to @equipment
		else
			render 'edit'
		end
	end

	private
	def equipment_params
		params.require(:equipment).permit(:item, :description, :price, :kind, :display)
	end

	def merch_param
		params.require(:equipment).permit(:merchant)
	end

	def get_merchant(equipment)
		if !merch_param[:merchant].blank?
			merch = Merchant.find(merch_param[:merchant])
			equipment.merchant = merch
			equipment.save
		end
	end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :all]

	def index
		@flowers = Flower.where(display: true)
	end

	def all
		@flowers = Flower.all
		render :index
	end

	def show
		@flower = Flower.find(params[:id])
	end

	def new
		authorize User
		@flower = Flower.new
	end

	def create
		authorize User
		@flower = Flower.new(flower_params)
		if @flower.save
			get_merchant(@flower)
			redirect_to @flower
		else
			render 'new'
		end
	end

	def edit
		authorize User
		@flower = Flower.find(params[:id])
	end

	def update
		authorize User
		@flower = Flower.find(params[:id])
		if @flower.update(flower_params)
			get_merchant(@flower)
			redirect_to @flower
		else
			render 'edit'
		end
	end

	private

	def flower_params
		params.require(:flower).permit(:strain, :kind, :description, :quantity_price, :display, :rec_med)
	end

	def merch_param
		params.require(:flower).permit(:merchant)
	end

	def get_merchant(flower)
		if !merch_param[:merchant].blank?
			merch = Merchant.find(merch_param[:merchant])
			flower.merchant = merch
			flower.save
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@premium_merchant = Merchant.where(premium: true).sample
	end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concentrates_helper.rb
module ConcentratesHelper
end

app/helpers/edibles_helper.rb
module EdiblesHelper
end

app/helpers/equip_lics_helper.rb
module EquipLicsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/panel.html.erb
<div class="row">
	<div class="large-11 large-offset-1 columns">
		<h1 class="text-center">Admin Panel</h1>
		<div class="text-center">
			<h3><%=link_to("Add a new Flower", new_flower_path)%></h3>
			<h3><%=link_to("Add a new Merchant", new_merchant_path)%></h3>
			<h3><%=link_to("Add equipment/license/property", new_equipment_path)%></h3>
			<h3><%=link_to("See all Merchants", merchants_path)%></h3>
		</div>
		<div class="row">
			<div class="large-6 columns">
				<h3>Add a new Concentrate <small>Pick a company</small></h3>
				<ul>
					<% @concentrates.each do |merch| %>
					<li>
					<%=link_to(merch.name, new_merchant_concentrate_path(merch))%>
					<span class="right"><%=link_to("Edit company", edit_merchant_path(merch))%></span>
					</li>
					<% end %>
				</ul>
			</div>
			<div class="large-6 columns">
				<h3>Edible Companies <small>Pick a company</small></h3>
				<ul>
					<% @edibles.each do |merch| %>
					<li><%= link_to(merch.name, new_merchant_edible_path(merch))%> 
					<span class="right"><%=link_to("Edit company", edit_merchant_path(merch))%></span>
					</li>
					<% end %>
				</ul>
			</div>
		</div>
		
		
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Cannabrokers Network</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<%= render 'partials/nav' %>
    <%= yield %>
    <%= render 'partials/footer' %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/partials/_concentrate_fields.html.erb
<%= form_for [@merchant, @concentrate] do |f| %>
	<% if @concentrate.errors.any? %>
		<div id="error_explanation">
			<h2><%=pluralize(@concentrate.errors.count, "error")%> prevented this Concentrate from being saved:</h2>
			<ul>
				<% @concentrate.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<p>
	<%=f.label :kind %>
	<%=f.text_field :kind %>
</p>

<p>
	<%=f.label :strain %>
	<%=f.text_field :strain %>
</p>

<p>
	<%=f.label :"Quantity / Price" %>
	<%=f.text_field :quantity_price %>
</p>

<p>
	<%=f.label :fees %>
	<%=f.text_field :fees %>
</p>

<p>
	<%= f.label :"Recrational / Medical" %>
	<%= f.text_field :rec_med %>
</p>

<p>
	<%= f.label :display %>
	<%= f.check_box :display %>
</p>

<%=f.submit class: "button" %>
<% end %>

app/views/partials/_edible_fields.html.erb
<%= form_for [@merchant, @edible] do |f| %>
<% if @edible.errors.any? %>
		<div id="error_explanation">
			<h2><%=pluralize(@edible.errors.count, "error")%> prevented this edible from being saved:</h2>
			<ul>
				<% @edible.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<p>
	<%=f.label :name %>
	<%=f.text_field :name %>
</p>
<p>
	<%=f.label :description %>
	<%=f.text_area :description %>
</p>

<p>
	<%=f.label :price %>
	<%=f.text_field :price %>
</p>

<p>
	<%= f.label :"Recrational / Medical" %>
	<%= f.text_field :rec_med %>
</p>

<p>
	<%= f.label :display %>
	<%= f.check_box :display %>
</p>

<%= f.submit class: "button" %>
<% end %>

app/views/partials/_equipment_fields.html.erb
<%= form_for @equipment do |f| %>
<% if @equipment.errors.any? %>
		<div id="error_explanation">
			<h2><%=pluralize(@equipment.errors.count, "error")%> prevented this flower from being saved:</h2>
			<ul>
				<% @equipment.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<p>
	<%=f.label :item %>
	<%=f.text_field :item %>
</p>

<p>
	<%= f.label :merchant %>
	<%= f.collection_select :merchant, Merchant.all, :id, :name, {include_blank: true} %>
</p>

<p>
	<%= f.label :kind %>
	<%= f.select :kind, Equipment.all.collect {|flower| flower.kind}.uniq %>
</p>

<p>
	<%= f.label :description %>
	<%= f.text_area :description%>
</p>

<p>
	<%= f.label :price%>
	<%= f.text_field :price%>
</p>

<p>
	<%= f.label :display %>
	<%= f.check_box :display %>
</p>

<%= f.submit class:"button" %>

<% end %>

app/views/partials/_flower_fields.html.erb
<%= form_for @flower do |f| %>
<% if @flower.errors.any? %>
		<div id="error_explanation">
			<h2><%=pluralize(@flower.errors.count, "error")%> prevented this flower from being saved:</h2>
			<ul>
				<% @flower.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<p>
	<%=f.label :strain %>
	<%=f.text_field :strain %>
</p>

<p>
	<%= f.label :merchant %>
	<%= f.collection_select :merchant, Merchant.all, :id, :name, {include_blank: true} %>
</p>

<p>
	<%= f.label :kind %>
	<%= f.select :kind, Flower.all.collect {|flower| flower.kind}.uniq %>
</p>

<p>
	<%= f.label :description %>
	<%= f.text_area :description%>
</p>

<p>
	<%= f.label :"Quantity / Price"%>
	<%= f.text_field :"quantity_price"%>
</p>

<p>
	<%= f.label :"Recrational / Medical" %>
	<%= f.text_field :rec_med %>
</p>

<p>
	<%= f.label :display %>
	<%= f.check_box :display %>
</p>

<%= f.submit class:"button" %>

<% end %>

app/views/partials/_footer.html.erb
<!-- ######################## Footer ######################## -->

<footer>

      <div class="row">

          <div class="twelve columns footer">
          	<p>&copy; CannaBrokers Network 2014</p>
          	<p>DISCLAIMER-Cannabrokers Network is an information website only. We do not buy or sell Medical/Recreational Cannabis.</p>
          </div>
      </div>

</footer>

app/views/partials/_mantis_ad_network.html.erb
<div data-mantis-zone='cannabrokersnetwork'></div>

<script type="text/javascript">
	MANTIS = {
		site: '54272a6b68e1050b00cc2528'
	};
</script>
<script type="text/javascript">
	var z = document.createElement("script");
	z.type = "text/javascript";
	z.async = true;
	z.src = "//assets.mantisadnetwork.com/mantodea.min.js";
	var s = document.getElementsByTagName('head')[0];
	s.parentNode.insertBefore(z, s);
</script>

app/views/partials/_merchant_fields.html.erb
<%=form_for @merchant do |f| %>
	<% if @merchant.errors.any? %>
		<div id="error_explanation">
			<h2><%=pluralize(@merchant.errors.count, "error")%> prevented this Merchant from being saved:</h2>
			<ul>
				<% @merchant.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
			<p>
				<%=f.label :name %>
				<%=f.text_field :name %>
			</p>

			<p>
				<%=f.label :description %>
				<%=f.text_area :description %>
			</p>

			<p>
				<%=f.label :phone %>
				<%=f.phone_field :phone %>
			</p>

			<p>
				<%=f.label :email %>
				<%=f.email_field :email %>
			</p>

			<p>
				<%=f.label :premium_merchant? %>
				<%=f.check_box :premium %>
			</p>

			<p>
				<%=f.label :"Recreational / Medical" %>
				<%=f.text_field :rec_med %>
			</p>

			<p>
				<%=f.submit class: "button"%>
			</p>
		<% end %>

app/views/partials/_nav.html.erb
<nav>

 <div class="twelve columns header_nav">
   <div class="row">
    <% flash.each do |name, msg| %>
      <%=content_tag :span, msg, class: "label alert" %>
    <% end %>
    <ul id="menu-header" class="nav-bar horizontal">

      <li><%=image_tag('cbkrs.png', width: 96)%></li>

      <li><%=link_to("Flowers", flowers_path)%></li>
      <li><%=link_to("Edibles", merchants_edibles_path)%></li>
      <li><%=link_to("Concentrates", merchants_concentrates_path)%></li>
      <li><%=link_to("Equipment-Licenses-Property", equipment_index_path)%></li>
      <li><strong>720-518-6733</strong></li>

    </ul>
    <script type="text/javascript">
         //<![CDATA[
         $('ul#menu-header').nav-bar();
          //]]>
        </script>

      </div>
    </div>

  </nav>