config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'

  get 'merchants/edibles' => 'merchants#edibles'
  get 'merchants/concentrates' => 'merchants#concentrates'
  get 'flowers/all' => 'flowers#all'
  get 'admin' => 'admin#panel'

  resources :merchants do
    get 'edibles/all' => 'edibles#all'
    get 'concentrates/all' => 'concentrates#all'
    resources :edibles
    resources :concentrates
    resources :flowers, only: [:show, :index]
  end

  resources :flowers
  get 'equipment/all' => 'equipment#all'
  resources :equipment

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  belongs_to :merchant

  validates :item, presence: true
  validates :price, presence: true
  validates :kind, presence: true
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :all]

	def index
		@equipments = Equipment.where(display: true)
	end

	def all
		@equipments = Equipment.all
		render :index
	end

	def show
		@equipment = Equipment.find(params[:id])
	end

	def new
		authorize User
		@equipment = Equipment.new
	end

	def edit
		authorize User
		@equipment = Equipment.find(params[:id])
	end

	def create
		authorize User
		@equipment = Equipment.new(equipment_params)
		if @equipment.save
			get_merchant(@equipment)
			redirect_to @equipment
		else
			render 'new'
		end
	end

	def update
		authorize User
		@equipment = Equipment.find(params[:id])
		if @equipment.update(equipment_params)
			get_merchant(@equipment)
			redirect_to @equipment
		else
			render 'edit'
		end
	end

	private
	def equipment_params
		params.require(:equipment).permit(:item, :description, :price, :kind, :display)
	end

	def merch_param
		params.require(:equipment).permit(:merchant)
	end

	def get_merchant(equipment)
		if !merch_param[:merchant].blank?
			merch = Merchant.find(merch_param[:merchant])
			equipment.merchant = merch
			equipment.save
		end
	end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/edit.html.erb
<div class="row">
	<div class="large-11 large-offset-1 columns">
		<h3>Edit Equipment/License/Property</h3>

		<%= render 'partials/equipment_fields' %>

	</div>
</div>

app/views/equipment/index.html.erb
<div class="row">
	<div class="large-11 large-offset-1 columns">
		<h3>Equipment - Liceneses - Property</h3>
		<% if current_user && current_user.admin? %>
			<%=link_to("See All Equipment - Including inactive", equipment_all_path)%>
		<% end %>
		<table>
			<thead>
				<tr>
					<th>Item name</th>
					<th>Description</th>
					<th>Kind</th>
					<th>Price</th>
					<% if current_user && current_user.admin? %>
						<th>Edit</th>
					<% end %>
				</tr>
			</thead>
			<tbody>
			<%@equipments.each do |equipment|%>
				<tr>
					<td><%=link_to(equipment.item, equipment_path(equipment))%></td>
					<td><%=equipment.description[0..40]%>...</td>
					<td><%=equipment.kind%></td>
					<td><%=equipment.price%></td>
					<% if current_user && current_user.admin? %>
						<td><%=link_to("Edit", edit_equipment_path(equipment))%></td>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>

		<%= render 'partials/mantis_ad_network' %>

	</div>
</div>

app/views/equipment/new.html.erb
<div class="row">
	<div class="large-11 large-offset-1 columns">
		<h3>New Equipment/License/Property</h3>

		<%= render 'partials/equipment_fields' %>

	</div>
</div>

app/views/equipment/show.html.erb
<div class="row">
	<div class="large-10 large-2-offset columns">
		<h3><%=@equipment.item%> <small>equipment</small></h3>
		<div class="panel">
		<span>Price/Quantity: <%=@equipment.price%></span>
		<span class="right"><%=@equipment.kind%> </span>
		</div>
		<p><%=@equipment.description%></p>
		<%= render 'partials/mantis_ad_network' %>
	</div>
</div>