config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'

  get 'merchants/edibles' => 'merchants#edibles'
  get 'merchants/concentrates' => 'merchants#concentrates'
  get 'flowers/all' => 'flowers#all'
  get 'admin' => 'admin#panel'

  resources :merchants do
    get 'edibles/all' => 'edibles#all'
    get 'concentrates/all' => 'concentrates#all'
    resources :edibles
    resources :concentrates
    resources :flowers, only: [:show, :index]
  end

  resources :flowers
  get 'equipment/all' => 'equipment#all'
  resources :equipment

end

app/models/flower.rb
class Flower < ActiveRecord::Base
	belongs_to :merchant

	validates :strain, presence: true
	validates :kind, presence: true
	validates :quantity_price, presence: true
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :all]

	def index
		@flowers = Flower.where(display: true)
	end

	def all
		@flowers = Flower.all
		render :index
	end

	def show
		@flower = Flower.find(params[:id])
	end

	def new
		authorize User
		@flower = Flower.new
	end

	def create
		authorize User
		@flower = Flower.new(flower_params)
		if @flower.save
			get_merchant(@flower)
			redirect_to @flower
		else
			render 'new'
		end
	end

	def edit
		authorize User
		@flower = Flower.find(params[:id])
	end

	def update
		authorize User
		@flower = Flower.find(params[:id])
		if @flower.update(flower_params)
			get_merchant(@flower)
			redirect_to @flower
		else
			render 'edit'
		end
	end

	private

	def flower_params
		params.require(:flower).permit(:strain, :kind, :description, :quantity_price, :display, :rec_med)
	end

	def merch_param
		params.require(:flower).permit(:merchant)
	end

	def get_merchant(flower)
		if !merch_param[:merchant].blank?
			merch = Merchant.find(merch_param[:merchant])
			flower.merchant = merch
			flower.save
		end
	end

end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/views/flowers/edit.html.erb
<div class="row">
	<div class="large-11 large-offset-1 columns">
	<h3>Edit Flower</h3>
		<%= render 'partials/flower_fields'%>
	</div>
</div>

app/views/flowers/index.html.erb
<div class="row">
	<div class="large-11 large-offset-1 columns">
		<h3>Flower</h3>
		<% if current_user && current_user.admin? %>
			<%=link_to("See All Flowers - Including inactive",flowers_all_path)%>
		<% end %>
		<table>
			<thead>
				<tr>
					<th>Strain name</th>
					<th>Sativa - Indica - High CBD</th>
					<th>Description</th>
					<th>Quantity</th>
					<th>Recreational / Medical</th>
					<% if current_user && current_user.admin? %>
						<th>Edit</th>
					<% end %>
				</tr>
			</thead>
			<tbody>
			<%@flowers.each do |flower|%>
				<tr>
					<td><%=link_to(flower.strain, flower_path(flower))%></td>
					<td><%=flower.kind%></td>
					<td><%=flower.description[0..40]%>...</td>
					<td><%=flower.quantity_price%></td>
					<td><%=flower.rec_med%></td>
					<% if current_user && current_user.admin? %>
						<td><%=link_to("Edit", edit_flower_path(flower))%></td>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>

		<%= render 'partials/mantis_ad_network' %>

	</div>
</div>

app/views/flowers/new.html.erb
<div class="row">
	<div class="large-11 large-offset-1 columns">
		<h3>New Flower</h3>

		<%= render 'partials/flower_fields' %>
		
	</div>
</div>

app/views/flowers/show.html.erb
<div class="row">
	<div class="large-10 large-2-offset columns">
		<h3><%=@flower.strain%> <small>flower</small></h3>
		<% if current_user && current_user.admin? %>
			<%=link_to("Edit", edit_flower_path(@flower))%>
		<% end %>
		<div class="panel">
		<span>Price/Quantity: <%=@flower.quantity_price%></span>
		<span class="right"><%=@flower.kind%> </span>
		</div>
		<p><%=@flower.description%></p>
		<%= render 'partials/mantis_ad_network' %>
	</div>
</div>