config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'

  get 'merchants/edibles' => 'merchants#edibles'
  get 'merchants/concentrates' => 'merchants#concentrates'
  get 'flowers/all' => 'flowers#all'
  get 'admin' => 'admin#panel'

  resources :merchants do
    get 'edibles/all' => 'edibles#all'
    get 'concentrates/all' => 'concentrates#all'
    resources :edibles
    resources :concentrates
    resources :flowers, only: [:show, :index]
  end

  resources :flowers
  get 'equipment/all' => 'equipment#all'
  resources :equipment

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
	has_many :flowers
	has_many :concentrates
	has_many :edibles
	has_many :equipments

	validates :name, presence: true
	validates :phone, presence: true
	validates :email, presence: true
	validates :email, format: { with: /.+@.+\..+/i, message: "improper format" }

	def self.edible_companies
		self.includes(:edibles).order('premium DESC').each_with_object([]) {|m, a| m.edibles.any? ? a << m : false }
	end

	def self.active_edible_companies
		self.includes(:edibles).order('premium DESC').where( edibles: {display: true} )
	end

	def self.concentrate_companies
		self.includes(:concentrates).order('premium DESC').each_with_object([]) {|m, a| m.concentrates.any? ? a << m : false }
	end

	def self.active_concentrate_companies
		self.includes(:concentrates).order('premium DESC').where( concentrates: {display: true} )
	end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
	before_action :authenticate_user!, only: [:index, :new, :create, :update, :edit]

	def index
		authorize User
		@merchants = Merchant.all
	end

	def show
		@merchant = Merchant.find(params[:id])
	end

	def edibles
		@merchants = Merchant.active_edible_companies
	end

	def concentrates
		@merchants = Merchant.active_concentrate_companies
	end

	def new
		authorize User
		@merchant = Merchant.new
	end

	def create
		authorize User
		@merchant = Merchant.new(merch_params)
		if @merchant.save
			redirect_to @merchant
		else
			render 'new'
		end
	end

	def edit
		authorize User
		@merchant = Merchant.find(params[:id])
	end

	def update
		authorize User
		@merchant = Merchant.find(params[:id])
		if @merchant.update(merch_params)
			redirect_to @merchant
		else
			render 'edit'
		end
	end

	private

	def merch_params
		params.require(:merchant).permit(:name, :description, :phone, :email, :premium, :rec_med)
	end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/concentrates.html.erb
<div class="row">
	<div class="large-10 large-offset-1 columns">
		<h3>Concentrate Companies</h3>
		<table>
			<thead>
				<tr>
					<th>Company</th>
					<th>Website</th>
					<th>Phone #</th>
					<th>Email</th>
					<th>Recreational / Medical</th>
				</tr>
			</thead>
			<tbody>
				<% @merchants.each do |merchant| %>
				<tr>
					<td><%=link_to(merchant.name, merchant_concentrates_path(merchant))%>
						<%if merchant.premium %>
					<span class="label success radius">premium</span>
					<%end%>
					</td>
					<td><a href="<%=merchant.description%>"><%=merchant.description%></a></td>
					<td><%=merchant.phone%></td>
					<td><%=merchant.email%></td>
					<td><%=merchant.rec_med%></td>
				</tr>
				<%end%>
			</tbody>
		</table>
		<%= render 'partials/mantis_ad_network' %>
	</div>
</div>

app/views/merchants/edibles.html.erb
<div class="row">
	<div class="large-10 columns">
		<h3>Edible Companies</h3>
		<table>
			<thead>
				<tr>
					<th>Company</th>
					<th>Website</th>
					<th>Phone #</th>
					<th>Email</th>
					<th>Recreational / Medical</th>
				</tr>
			</thead>
			<tbody>
				<% @merchants.each do |merchant| %>
				<tr>
					<td><%=link_to(merchant.name, merchant_edibles_path(merchant))%> 
					<%if merchant.premium %>
					<span class="label success radius"> premium </span>
					<%end%>
					</td>
					<td><a href="<%=merchant.description%>"><%=merchant.description%></a></td>
					<td><%=merchant.phone%></td>
					<td><%=merchant.email%></td>
					<td><%=merchant.rec_med%></td>
				</tr>
				<%end%>
			</tbody>
		</table>

		<%= render 'partials/mantis_ad_network' %>
	</div>
</div>

app/views/merchants/edit.html.erb
<div class="row">
	<div class="large-11 large-offset-1 columns">
		<h3>Edit Merchant</h3>

		<%= render 'partials/merchant_fields' %>
	</div>
</div>

app/views/merchants/index.html.erb
<div class="row">
	<div class="large-10 large-offset-1 columns">
		<h3>All Merchants</h3>
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>add flower</th>
					<th>add edible</th>
					<th>add concentrate</th>
					<th>edit</th>
				</tr>
			</thead>
			<tbody>
			<% @merchants.each do |merch|%>
				<tr>
					<td><%=link_to(merch.name, merchant_path(merch))%></td>
					<td><%=link_to("add Flower", new_flower_path)%></td>
					<td><%=link_to("add Edible", new_merchant_edible_path(merch))%></td>
					<td><%=link_to("add Concentrate", new_merchant_concentrate_path(merch))%></td>
					<td><%=link_to("Edit Mechant", edit_merchant_path(merch))%></td>
				</tr>
			<% end %>
			</tbody>
		</table>

	

	</div>
</div>

app/views/merchants/new.html.erb
<div class="row">
	<div class="large-11 large-offset-1 columns">
		<h3>New Merchant</h3>

		<%= render 'partials/merchant_fields' %>
	</div>
</div>

app/views/merchants/show.html.erb
<div class="row">
	<div class="large-10 large-offset-2 columns">
		<h3><%=@merchant.name%>
			<% if @merchant.premium %>
				<span class="label success radius">Premium</span>
			<% end %>
		</h3>
		<ul class="inline-list">
			<li>Email: <%=@merchant.email%></li>
			<li>Phone: <%=@merchant.phone%></li>
		</ul>
		<p><%=@merchant.description%></p>
		<div class="row">
			<div class="large-4 columns">
				<h3>Edibles <small>
					<% if current_user && current_user.admin? %>
						<%=link_to("add", new_merchant_edible_path(@merchant))%>
					<% end %>
				</small>
				</h3>
				<ul>
				<%@merchant.edibles.each do |edible|%>
					<li><%=link_to(edible.name, merchant_edible_path(@merchant, edible))%></li>
				<%end%>
				</ul>
			</div>
			<div class="large-4 columns">
				<h3>Concentrates <small>
					<% if current_user && current_user.admin? %>
						<%=link_to("add", new_merchant_concentrate_path(@merchant))%>
					<% end %>
				</small>
				</h3>
				<ul>
				<%@merchant.concentrates.each do |concentrate|%>
					<li><%=link_to(concentrate.strain, merchant_concentrate_path(@merchant, concentrate))%></li>
				<%end%>
				</ul>
			</div>
			<div class="large-4 columns">
				<h3>Flowers
					<small>
						<% if current_user && current_user.admin? %>
						<%=link_to("add", new_flower_path)%>
					<% end %>
					</small>
				</h3>
				<ul>
					<%@merchant.flowers.each do |flower|%>
						<li><%=link_to(flower.strain, flower_path(flower))%></li>
					<%end%>
				</ul>
			</div>
		</div>
		<%= render 'partials/mantis_ad_network' %>
	</div>
</div>